# bwa_index_name: Homo_sapiens.GRCh38.dna.primary_assembly.fa
# bwa_index_dir: /gpfs/hpchome/a72094/rocket/annotations/GRCh38/bwa_index/
# chromosome_lengths: /gpfs/hpchome/a72094/rocket/annotations/GRCh38/chromosome_lengths.txt
# PU1_peaks_gtf: /gpfs/hpchome/yurii95/DeepChromatinPy/data/PU1/processed/PU1/annotations/PU1.peaks.gtf
bt_index_name: genome.fa
bt_basename: genome
bt_index_dir: landerlab-bowtie-hg19-index/
chromosome_lengths: landerlab-bowtie-hg19-index/chromosome_lengths.txt
dictionary: landerlab-bowtie-hg19-index-misc/genome.dict
samples: [NA06985_PU1]
# PU1_peaks_gtf: /home/jupyter/DATA/Blood_ATAC/processed/PU1/peaks/NA06985_PU1.no_duplicates.saf
# samples: [NA06985_PU1,NA06986_PU1,NA06994_PU1,NA07037_PU1,NA07048_PU1,NA07051_PU1,NA07056_PU1,NA07346_PU1,NA07357_PU1,NA10847_PU1,NA10851_PU1,NA11829_PU1,NA11830_PU1,NA11831_PU1,NA11832_PU1,NA11840_PU1,NA11881_PU1,NA11894_PU1,NA11918_PU1,NA11920_PU1,NA11931_PU1,NA11992_PU1,NA11993_PU1,NA11994_PU1,NA12005_PU1,NA12043_PU1,NA12154_PU1,NA12156_PU1,NA12234_PU1,NA12249_PU1,NA12275_PU1,NA12282_PU1,NA12286_PU1,NA12287_PU1,NA12383_PU1,NA12489_PU1,NA12750_PU1,NA12760_PU1,NA12761_PU1,NA12762_PU1,NA12763_PU1,NA12776_PU1,NA12812_PU1,NA12813_PU1,NA12814_PU1,NA12815_PU1,NA12873_PU1]
files: [IP_06985_PU1_120521_6_sorted]
# files: [IP_06985_PU1_120521_6_sorted, IP_06986_PU1_120605_7_sorted, IP_06994_PU1_120605_4_sorted, IP_07037_PU1_120521_7_sorted, IP_07048_PU1_120521_8_sorted, IP_07051_PU1_merge_sorted, IP_07056_PU1_120605_4_sorted, IP_07346_PU1_120605_6_sorted, IP_07357_PU1_120612_1_sorted, IP_10847_PU1_120612_7_sorted, IP_10851_PU1_120605_3_sorted, IP_11829_PU1_120521_1_sorted, IP_11830_PU1_merge_sorted, IP_11831_PU1_merge_sorted, IP_11832_PU1_120612_2_sorted, IP_11840_PU1_merge_sorted, IP_11881_PU1_120612_1_sorted, IP_11894_PU1_120521_2_sorted, IP_11918_PU1_120521_3_sorted, IP_11920_PU1_120605_4_sorted, IP_11931_PU1_120605_8_sorted, IP_11992_PU1_120612_1_sorted, IP_11993_PU1_120521_5_sorted, IP_11994_PU1_120605_7_sorted, IP_12005_PU1_120605_7_sorted, IP_12043_PU1_120605_5_sorted, IP_12154_PU1_120521_6_sorted, IP_12156_PU1_120605_5_sorted, IP_12234_PU1_120612_6_sorted, IP_12249_PU1_120612_4_sorted, IP_12275_PU1_120605_3_sorted, IP_12282_PU1_120521_7_sorted, IP_12286_PU1_120521_8_sorted, IP_12287_PU1_120605_6_sorted, IP_12383_PU1_120605_6_sorted, IP_12489_PU1_120605_7_sorted, IP_12750_PU1_120521_1_sorted, IP_12760_PU1_merge_sorted, IP_12761_PU1_120521_2_sorted, IP_12762_PU1_merge_sorted, IP_12763_PU1_120612_4_sorted, IP_12776_PU1_120605_5_sorted, IP_12812_PU1_120605_8_sorted, IP_12813_PU1_120521_4_sorted, IP_12814_PU1_merge_sorted, IP_12815_PU1_120605_8_sorted, IP_12873_PU1_merge_sorted]


#QTL mapping
conditions: ["PU1"]
n_batches: 250
qtl_vcf: "/gpfs/hpchome/a72094/rocket/datasets/PU.1/genotypes/vcf/GRCh38/Waszak_47_samples.merged.vcf.gz"
cis_window: 50000
nominal_cis_window: 50000
annot_type: ["cqn"]

#Software paths
picard_path: /home/jupyter/DATA/software/picard.jar
